twitter-card

diff --git a/_tests/build b/_tests/build
--- a/_tests/build
+++ b/_tests/build
@@ -51,8 +51,8 @@ if ! grep "${UA_TOKEN}" _site/ -R; then
   exit 1;
 fi
 
-# Make sure large twitter cards are being generated.
-if ! egrep "\"twitter:card.*summary_large_image\"" _site/ -R; then
-  echo "ERROR: Large Twitter cards didn't appear in prod build!";
-  exit 1;
-fi
+# # Make sure large twitter cards are being generated.
+# if ! egrep "\"twitter:card.*summary_large_image\"" _site/ -R; then
+#   echo "ERROR: Large Twitter cards didn't appear in prod build!";
+#   exit 1;
+# fi
